// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	firecrawl "github.com/sells-group/research-cli/pkg/firecrawl"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BatchScrape provides a mock function with given fields: ctx, req
func (_m *MockClient) BatchScrape(ctx context.Context, req firecrawl.BatchScrapeRequest) (*firecrawl.BatchScrapeResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for BatchScrape")
	}

	var r0 *firecrawl.BatchScrapeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, firecrawl.BatchScrapeRequest) (*firecrawl.BatchScrapeResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, firecrawl.BatchScrapeRequest) *firecrawl.BatchScrapeResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*firecrawl.BatchScrapeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, firecrawl.BatchScrapeRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_BatchScrape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchScrape'
type MockClient_BatchScrape_Call struct {
	*mock.Call
}

// BatchScrape is a helper method to define mock.On call
//   - ctx context.Context
//   - req firecrawl.BatchScrapeRequest
func (_e *MockClient_Expecter) BatchScrape(ctx interface{}, req interface{}) *MockClient_BatchScrape_Call {
	return &MockClient_BatchScrape_Call{Call: _e.mock.On("BatchScrape", ctx, req)}
}

func (_c *MockClient_BatchScrape_Call) Run(run func(ctx context.Context, req firecrawl.BatchScrapeRequest)) *MockClient_BatchScrape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(firecrawl.BatchScrapeRequest))
	})
	return _c
}

func (_c *MockClient_BatchScrape_Call) Return(_a0 *firecrawl.BatchScrapeResponse, _a1 error) *MockClient_BatchScrape_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_BatchScrape_Call) RunAndReturn(run func(context.Context, firecrawl.BatchScrapeRequest) (*firecrawl.BatchScrapeResponse, error)) *MockClient_BatchScrape_Call {
	_c.Call.Return(run)
	return _c
}

// Crawl provides a mock function with given fields: ctx, req
func (_m *MockClient) Crawl(ctx context.Context, req firecrawl.CrawlRequest) (*firecrawl.CrawlResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Crawl")
	}

	var r0 *firecrawl.CrawlResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, firecrawl.CrawlRequest) (*firecrawl.CrawlResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, firecrawl.CrawlRequest) *firecrawl.CrawlResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*firecrawl.CrawlResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, firecrawl.CrawlRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Crawl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Crawl'
type MockClient_Crawl_Call struct {
	*mock.Call
}

// Crawl is a helper method to define mock.On call
//   - ctx context.Context
//   - req firecrawl.CrawlRequest
func (_e *MockClient_Expecter) Crawl(ctx interface{}, req interface{}) *MockClient_Crawl_Call {
	return &MockClient_Crawl_Call{Call: _e.mock.On("Crawl", ctx, req)}
}

func (_c *MockClient_Crawl_Call) Run(run func(ctx context.Context, req firecrawl.CrawlRequest)) *MockClient_Crawl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(firecrawl.CrawlRequest))
	})
	return _c
}

func (_c *MockClient_Crawl_Call) Return(_a0 *firecrawl.CrawlResponse, _a1 error) *MockClient_Crawl_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Crawl_Call) RunAndReturn(run func(context.Context, firecrawl.CrawlRequest) (*firecrawl.CrawlResponse, error)) *MockClient_Crawl_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatchScrapeStatus provides a mock function with given fields: ctx, id
func (_m *MockClient) GetBatchScrapeStatus(ctx context.Context, id string) (*firecrawl.BatchScrapeStatusResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchScrapeStatus")
	}

	var r0 *firecrawl.BatchScrapeStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*firecrawl.BatchScrapeStatusResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *firecrawl.BatchScrapeStatusResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*firecrawl.BatchScrapeStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetBatchScrapeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchScrapeStatus'
type MockClient_GetBatchScrapeStatus_Call struct {
	*mock.Call
}

// GetBatchScrapeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClient_Expecter) GetBatchScrapeStatus(ctx interface{}, id interface{}) *MockClient_GetBatchScrapeStatus_Call {
	return &MockClient_GetBatchScrapeStatus_Call{Call: _e.mock.On("GetBatchScrapeStatus", ctx, id)}
}

func (_c *MockClient_GetBatchScrapeStatus_Call) Run(run func(ctx context.Context, id string)) *MockClient_GetBatchScrapeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetBatchScrapeStatus_Call) Return(_a0 *firecrawl.BatchScrapeStatusResponse, _a1 error) *MockClient_GetBatchScrapeStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetBatchScrapeStatus_Call) RunAndReturn(run func(context.Context, string) (*firecrawl.BatchScrapeStatusResponse, error)) *MockClient_GetBatchScrapeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetCrawlStatus provides a mock function with given fields: ctx, id
func (_m *MockClient) GetCrawlStatus(ctx context.Context, id string) (*firecrawl.CrawlStatusResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCrawlStatus")
	}

	var r0 *firecrawl.CrawlStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*firecrawl.CrawlStatusResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *firecrawl.CrawlStatusResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*firecrawl.CrawlStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetCrawlStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCrawlStatus'
type MockClient_GetCrawlStatus_Call struct {
	*mock.Call
}

// GetCrawlStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClient_Expecter) GetCrawlStatus(ctx interface{}, id interface{}) *MockClient_GetCrawlStatus_Call {
	return &MockClient_GetCrawlStatus_Call{Call: _e.mock.On("GetCrawlStatus", ctx, id)}
}

func (_c *MockClient_GetCrawlStatus_Call) Run(run func(ctx context.Context, id string)) *MockClient_GetCrawlStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetCrawlStatus_Call) Return(_a0 *firecrawl.CrawlStatusResponse, _a1 error) *MockClient_GetCrawlStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetCrawlStatus_Call) RunAndReturn(run func(context.Context, string) (*firecrawl.CrawlStatusResponse, error)) *MockClient_GetCrawlStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Scrape provides a mock function with given fields: ctx, req
func (_m *MockClient) Scrape(ctx context.Context, req firecrawl.ScrapeRequest) (*firecrawl.ScrapeResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Scrape")
	}

	var r0 *firecrawl.ScrapeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, firecrawl.ScrapeRequest) (*firecrawl.ScrapeResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, firecrawl.ScrapeRequest) *firecrawl.ScrapeResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*firecrawl.ScrapeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, firecrawl.ScrapeRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Scrape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scrape'
type MockClient_Scrape_Call struct {
	*mock.Call
}

// Scrape is a helper method to define mock.On call
//   - ctx context.Context
//   - req firecrawl.ScrapeRequest
func (_e *MockClient_Expecter) Scrape(ctx interface{}, req interface{}) *MockClient_Scrape_Call {
	return &MockClient_Scrape_Call{Call: _e.mock.On("Scrape", ctx, req)}
}

func (_c *MockClient_Scrape_Call) Run(run func(ctx context.Context, req firecrawl.ScrapeRequest)) *MockClient_Scrape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(firecrawl.ScrapeRequest))
	})
	return _c
}

func (_c *MockClient_Scrape_Call) Return(_a0 *firecrawl.ScrapeResponse, _a1 error) *MockClient_Scrape_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Scrape_Call) RunAndReturn(run func(context.Context, firecrawl.ScrapeRequest) (*firecrawl.ScrapeResponse, error)) *MockClient_Scrape_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
