// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockExtractor is an autogenerated mock type for the Extractor type
type MockExtractor struct {
	mock.Mock
}

type MockExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExtractor) EXPECT() *MockExtractor_Expecter {
	return &MockExtractor_Expecter{mock: &_m.Mock}
}

// ExtractText provides a mock function with given fields: ctx, pdfPath
func (_m *MockExtractor) ExtractText(ctx context.Context, pdfPath string) (string, error) {
	ret := _m.Called(ctx, pdfPath)

	if len(ret) == 0 {
		panic("no return value specified for ExtractText")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, pdfPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, pdfPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pdfPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExtractor_ExtractText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractText'
type MockExtractor_ExtractText_Call struct {
	*mock.Call
}

// ExtractText is a helper method to define mock.On call
//   - ctx context.Context
//   - pdfPath string
func (_e *MockExtractor_Expecter) ExtractText(ctx interface{}, pdfPath interface{}) *MockExtractor_ExtractText_Call {
	return &MockExtractor_ExtractText_Call{Call: _e.mock.On("ExtractText", ctx, pdfPath)}
}

func (_c *MockExtractor_ExtractText_Call) Run(run func(ctx context.Context, pdfPath string)) *MockExtractor_ExtractText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExtractor_ExtractText_Call) Return(_a0 string, _a1 error) *MockExtractor_ExtractText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExtractor_ExtractText_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockExtractor_ExtractText_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExtractor creates a new instance of MockExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtractor {
	mock := &MockExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
