app = "sells-worker"
primary_region = "dfw"

[build]

[env]
  RESEARCH_TEMPORAL_HOST_PORT = "sells-temporal.internal:7233"
  RESEARCH_TEMPORAL_NAMESPACE = "research-cli"

[processes]
  worker = "temporal-worker"

[[vm]]
  size = "performance-4x"
  memory = "8gb"
  processes = ["worker"]
