// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	salesforce "github.com/sells-group/research-cli/pkg/salesforce"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DescribeSObject provides a mock function with given fields: ctx, name
func (_m *MockClient) DescribeSObject(ctx context.Context, name string) (*salesforce.SObjectDescription, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DescribeSObject")
	}

	var r0 *salesforce.SObjectDescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*salesforce.SObjectDescription, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *salesforce.SObjectDescription); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*salesforce.SObjectDescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_DescribeSObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeSObject'
type MockClient_DescribeSObject_Call struct {
	*mock.Call
}

// DescribeSObject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockClient_Expecter) DescribeSObject(ctx interface{}, name interface{}) *MockClient_DescribeSObject_Call {
	return &MockClient_DescribeSObject_Call{Call: _e.mock.On("DescribeSObject", ctx, name)}
}

func (_c *MockClient_DescribeSObject_Call) Run(run func(ctx context.Context, name string)) *MockClient_DescribeSObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_DescribeSObject_Call) Return(_a0 *salesforce.SObjectDescription, _a1 error) *MockClient_DescribeSObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_DescribeSObject_Call) RunAndReturn(run func(context.Context, string) (*salesforce.SObjectDescription, error)) *MockClient_DescribeSObject_Call {
	_c.Call.Return(run)
	return _c
}

// InsertCollection provides a mock function with given fields: ctx, sObjectName, records
func (_m *MockClient) InsertCollection(ctx context.Context, sObjectName string, records []map[string]interface{}) ([]salesforce.CollectionResult, error) {
	ret := _m.Called(ctx, sObjectName, records)

	if len(ret) == 0 {
		panic("no return value specified for InsertCollection")
	}

	var r0 []salesforce.CollectionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []map[string]interface{}) ([]salesforce.CollectionResult, error)); ok {
		return rf(ctx, sObjectName, records)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []map[string]interface{}) []salesforce.CollectionResult); ok {
		r0 = rf(ctx, sObjectName, records)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]salesforce.CollectionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []map[string]interface{}) error); ok {
		r1 = rf(ctx, sObjectName, records)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_InsertCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertCollection'
type MockClient_InsertCollection_Call struct {
	*mock.Call
}

// InsertCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - sObjectName string
//   - records []map[string]interface{}
func (_e *MockClient_Expecter) InsertCollection(ctx interface{}, sObjectName interface{}, records interface{}) *MockClient_InsertCollection_Call {
	return &MockClient_InsertCollection_Call{Call: _e.mock.On("InsertCollection", ctx, sObjectName, records)}
}

func (_c *MockClient_InsertCollection_Call) Run(run func(ctx context.Context, sObjectName string, records []map[string]interface{})) *MockClient_InsertCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]map[string]interface{}))
	})
	return _c
}

func (_c *MockClient_InsertCollection_Call) Return(_a0 []salesforce.CollectionResult, _a1 error) *MockClient_InsertCollection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_InsertCollection_Call) RunAndReturn(run func(context.Context, string, []map[string]interface{}) ([]salesforce.CollectionResult, error)) *MockClient_InsertCollection_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOne provides a mock function with given fields: ctx, sObjectName, record
func (_m *MockClient) InsertOne(ctx context.Context, sObjectName string, record map[string]interface{}) (string, error) {
	ret := _m.Called(ctx, sObjectName, record)

	if len(ret) == 0 {
		panic("no return value specified for InsertOne")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (string, error)); ok {
		return rf(ctx, sObjectName, record)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) string); ok {
		r0 = rf(ctx, sObjectName, record)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, sObjectName, record)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_InsertOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOne'
type MockClient_InsertOne_Call struct {
	*mock.Call
}

// InsertOne is a helper method to define mock.On call
//   - ctx context.Context
//   - sObjectName string
//   - record map[string]interface{}
func (_e *MockClient_Expecter) InsertOne(ctx interface{}, sObjectName interface{}, record interface{}) *MockClient_InsertOne_Call {
	return &MockClient_InsertOne_Call{Call: _e.mock.On("InsertOne", ctx, sObjectName, record)}
}

func (_c *MockClient_InsertOne_Call) Run(run func(ctx context.Context, sObjectName string, record map[string]interface{})) *MockClient_InsertOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockClient_InsertOne_Call) Return(_a0 string, _a1 error) *MockClient_InsertOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_InsertOne_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) (string, error)) *MockClient_InsertOne_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, soql, out
func (_m *MockClient) Query(ctx context.Context, soql string, out interface{}) error {
	ret := _m.Called(ctx, soql, out)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, soql, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockClient_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - soql string
//   - out interface{}
func (_e *MockClient_Expecter) Query(ctx interface{}, soql interface{}, out interface{}) *MockClient_Query_Call {
	return &MockClient_Query_Call{Call: _e.mock.On("Query", ctx, soql, out)}
}

func (_c *MockClient_Query_Call) Run(run func(ctx context.Context, soql string, out interface{})) *MockClient_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockClient_Query_Call) Return(_a0 error) *MockClient_Query_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Query_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockClient_Query_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCollection provides a mock function with given fields: ctx, sObjectName, records
func (_m *MockClient) UpdateCollection(ctx context.Context, sObjectName string, records []salesforce.CollectionRecord) ([]salesforce.CollectionResult, error) {
	ret := _m.Called(ctx, sObjectName, records)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCollection")
	}

	var r0 []salesforce.CollectionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []salesforce.CollectionRecord) ([]salesforce.CollectionResult, error)); ok {
		return rf(ctx, sObjectName, records)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []salesforce.CollectionRecord) []salesforce.CollectionResult); ok {
		r0 = rf(ctx, sObjectName, records)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]salesforce.CollectionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []salesforce.CollectionRecord) error); ok {
		r1 = rf(ctx, sObjectName, records)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_UpdateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCollection'
type MockClient_UpdateCollection_Call struct {
	*mock.Call
}

// UpdateCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - sObjectName string
//   - records []salesforce.CollectionRecord
func (_e *MockClient_Expecter) UpdateCollection(ctx interface{}, sObjectName interface{}, records interface{}) *MockClient_UpdateCollection_Call {
	return &MockClient_UpdateCollection_Call{Call: _e.mock.On("UpdateCollection", ctx, sObjectName, records)}
}

func (_c *MockClient_UpdateCollection_Call) Run(run func(ctx context.Context, sObjectName string, records []salesforce.CollectionRecord)) *MockClient_UpdateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]salesforce.CollectionRecord))
	})
	return _c
}

func (_c *MockClient_UpdateCollection_Call) Return(_a0 []salesforce.CollectionResult, _a1 error) *MockClient_UpdateCollection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_UpdateCollection_Call) RunAndReturn(run func(context.Context, string, []salesforce.CollectionRecord) ([]salesforce.CollectionResult, error)) *MockClient_UpdateCollection_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOne provides a mock function with given fields: ctx, sObjectName, id, fields
func (_m *MockClient) UpdateOne(ctx context.Context, sObjectName string, id string, fields map[string]interface{}) error {
	ret := _m.Called(ctx, sObjectName, id, fields)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, sObjectName, id, fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_UpdateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOne'
type MockClient_UpdateOne_Call struct {
	*mock.Call
}

// UpdateOne is a helper method to define mock.On call
//   - ctx context.Context
//   - sObjectName string
//   - id string
//   - fields map[string]interface{}
func (_e *MockClient_Expecter) UpdateOne(ctx interface{}, sObjectName interface{}, id interface{}, fields interface{}) *MockClient_UpdateOne_Call {
	return &MockClient_UpdateOne_Call{Call: _e.mock.On("UpdateOne", ctx, sObjectName, id, fields)}
}

func (_c *MockClient_UpdateOne_Call) Run(run func(ctx context.Context, sObjectName string, id string, fields map[string]interface{})) *MockClient_UpdateOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]interface{}))
	})
	return _c
}

func (_c *MockClient_UpdateOne_Call) Return(_a0 error) *MockClient_UpdateOne_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_UpdateOne_Call) RunAndReturn(run func(context.Context, string, string, map[string]interface{}) error) *MockClient_UpdateOne_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
