// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	notionapi "github.com/jomei/notionapi"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreatePage provides a mock function with given fields: ctx, req
func (_m *MockClient) CreatePage(ctx context.Context, req *notionapi.PageCreateRequest) (*notionapi.Page, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePage")
	}

	var r0 *notionapi.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notionapi.PageCreateRequest) (*notionapi.Page, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notionapi.PageCreateRequest) *notionapi.Page); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notionapi.Page)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notionapi.PageCreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreatePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePage'
type MockClient_CreatePage_Call struct {
	*mock.Call
}

// CreatePage is a helper method to define mock.On call
//   - ctx context.Context
//   - req *notionapi.PageCreateRequest
func (_e *MockClient_Expecter) CreatePage(ctx interface{}, req interface{}) *MockClient_CreatePage_Call {
	return &MockClient_CreatePage_Call{Call: _e.mock.On("CreatePage", ctx, req)}
}

func (_c *MockClient_CreatePage_Call) Run(run func(ctx context.Context, req *notionapi.PageCreateRequest)) *MockClient_CreatePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*notionapi.PageCreateRequest))
	})
	return _c
}

func (_c *MockClient_CreatePage_Call) Return(_a0 *notionapi.Page, _a1 error) *MockClient_CreatePage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreatePage_Call) RunAndReturn(run func(context.Context, *notionapi.PageCreateRequest) (*notionapi.Page, error)) *MockClient_CreatePage_Call {
	_c.Call.Return(run)
	return _c
}

// QueryDatabase provides a mock function with given fields: ctx, dbID, req
func (_m *MockClient) QueryDatabase(ctx context.Context, dbID string, req *notionapi.DatabaseQueryRequest) (*notionapi.DatabaseQueryResponse, error) {
	ret := _m.Called(ctx, dbID, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryDatabase")
	}

	var r0 *notionapi.DatabaseQueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *notionapi.DatabaseQueryRequest) (*notionapi.DatabaseQueryResponse, error)); ok {
		return rf(ctx, dbID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *notionapi.DatabaseQueryRequest) *notionapi.DatabaseQueryResponse); ok {
		r0 = rf(ctx, dbID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notionapi.DatabaseQueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *notionapi.DatabaseQueryRequest) error); ok {
		r1 = rf(ctx, dbID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_QueryDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryDatabase'
type MockClient_QueryDatabase_Call struct {
	*mock.Call
}

// QueryDatabase is a helper method to define mock.On call
//   - ctx context.Context
//   - dbID string
//   - req *notionapi.DatabaseQueryRequest
func (_e *MockClient_Expecter) QueryDatabase(ctx interface{}, dbID interface{}, req interface{}) *MockClient_QueryDatabase_Call {
	return &MockClient_QueryDatabase_Call{Call: _e.mock.On("QueryDatabase", ctx, dbID, req)}
}

func (_c *MockClient_QueryDatabase_Call) Run(run func(ctx context.Context, dbID string, req *notionapi.DatabaseQueryRequest)) *MockClient_QueryDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*notionapi.DatabaseQueryRequest))
	})
	return _c
}

func (_c *MockClient_QueryDatabase_Call) Return(_a0 *notionapi.DatabaseQueryResponse, _a1 error) *MockClient_QueryDatabase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_QueryDatabase_Call) RunAndReturn(run func(context.Context, string, *notionapi.DatabaseQueryRequest) (*notionapi.DatabaseQueryResponse, error)) *MockClient_QueryDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePage provides a mock function with given fields: ctx, pageID, req
func (_m *MockClient) UpdatePage(ctx context.Context, pageID string, req *notionapi.PageUpdateRequest) (*notionapi.Page, error) {
	ret := _m.Called(ctx, pageID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePage")
	}

	var r0 *notionapi.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *notionapi.PageUpdateRequest) (*notionapi.Page, error)); ok {
		return rf(ctx, pageID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *notionapi.PageUpdateRequest) *notionapi.Page); ok {
		r0 = rf(ctx, pageID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notionapi.Page)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *notionapi.PageUpdateRequest) error); ok {
		r1 = rf(ctx, pageID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_UpdatePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePage'
type MockClient_UpdatePage_Call struct {
	*mock.Call
}

// UpdatePage is a helper method to define mock.On call
//   - ctx context.Context
//   - pageID string
//   - req *notionapi.PageUpdateRequest
func (_e *MockClient_Expecter) UpdatePage(ctx interface{}, pageID interface{}, req interface{}) *MockClient_UpdatePage_Call {
	return &MockClient_UpdatePage_Call{Call: _e.mock.On("UpdatePage", ctx, pageID, req)}
}

func (_c *MockClient_UpdatePage_Call) Run(run func(ctx context.Context, pageID string, req *notionapi.PageUpdateRequest)) *MockClient_UpdatePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*notionapi.PageUpdateRequest))
	})
	return _c
}

func (_c *MockClient_UpdatePage_Call) Return(_a0 *notionapi.Page, _a1 error) *MockClient_UpdatePage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_UpdatePage_Call) RunAndReturn(run func(context.Context, string, *notionapi.PageUpdateRequest) (*notionapi.Page, error)) *MockClient_UpdatePage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
