-- Compliance tables (Phase 2)

-- Create "osha_inspections" table
CREATE TABLE "fed_data"."osha_inspections" (
  "activity_nr" bigint NOT NULL,
  "estab_name" character varying(300) NULL,
  "site_city" character varying(100) NULL,
  "site_state" character(2) NULL,
  "site_zip" character varying(10) NULL,
  "naics_code" character varying(6) NULL,
  "sic_code" character varying(4) NULL,
  "open_date" date NULL,
  "close_case_date" date NULL,
  "case_type" character(1) NULL,
  "safety_hlth" character(1) NULL,
  "total_penalty" numeric(12,2) NULL,
  "updated_at" timestamptz NULL DEFAULT now(),
  PRIMARY KEY ("activity_nr")
);
-- Create index "idx_osha_naics" to table: "osha_inspections"
CREATE INDEX "idx_osha_naics" ON "fed_data"."osha_inspections" ("naics_code");
-- Create index "idx_osha_name" to table: "osha_inspections"
CREATE INDEX "idx_osha_name" ON "fed_data"."osha_inspections" USING GIN ("estab_name" public.gin_trgm_ops);

-- Create "epa_facilities" table
CREATE TABLE "fed_data"."epa_facilities" (
  "registry_id" character varying(50) NOT NULL,
  "fac_name" character varying(300) NULL,
  "fac_city" character varying(100) NULL,
  "fac_state" character varying(10) NULL,
  "fac_zip" character varying(20) NULL,
  "naics_codes" text[] NULL,
  "sic_codes" text[] NULL,
  "fac_lat" numeric(9,6) NULL,
  "fac_long" numeric(9,6) NULL,
  "updated_at" timestamptz NULL DEFAULT now(),
  PRIMARY KEY ("registry_id")
);
-- Create index "idx_epa_name" to table: "epa_facilities"
CREATE INDEX "idx_epa_name" ON "fed_data"."epa_facilities" USING GIN ("fac_name" public.gin_trgm_ops);
-- Create index "idx_epa_state" to table: "epa_facilities"
CREATE INDEX "idx_epa_state" ON "fed_data"."epa_facilities" ("fac_state");

-- Create "form_5500" table
CREATE TABLE "fed_data"."form_5500" (
  "ack_id" text NOT NULL,
  "form_plan_year_begin_date" text NULL,
  "form_tax_prd" text NULL,
  "type_plan_entity_cd" text NULL,
  "type_dfe_plan_entity_cd" text NULL,
  "initial_filing_ind" text NULL,
  "amended_ind" text NULL,
  "final_filing_ind" text NULL,
  "short_plan_yr_ind" text NULL,
  "collective_bargain_ind" text NULL,
  "f5558_application_filed_ind" text NULL,
  "ext_automatic_ind" text NULL,
  "dfvc_program_ind" text NULL,
  "ext_special_ind" text NULL,
  "ext_special_text" text NULL,
  "plan_name" text NULL,
  "spons_dfe_pn" text NULL,
  "plan_eff_date" text NULL,
  "sponsor_dfe_name" text NULL,
  "spons_dfe_dba_name" text NULL,
  "spons_dfe_care_of_name" text NULL,
  "spons_dfe_mail_us_address1" text NULL,
  "spons_dfe_mail_us_address2" text NULL,
  "spons_dfe_mail_us_city" text NULL,
  "spons_dfe_mail_us_state" text NULL,
  "spons_dfe_mail_us_zip" text NULL,
  "spons_dfe_mail_foreign_addr1" text NULL,
  "spons_dfe_mail_foreign_addr2" text NULL,
  "spons_dfe_mail_foreign_city" text NULL,
  "spons_dfe_mail_forgn_prov_st" text NULL,
  "spons_dfe_mail_foreign_cntry" text NULL,
  "spons_dfe_mail_forgn_postal_cd" text NULL,
  "spons_dfe_loc_us_address1" text NULL,
  "spons_dfe_loc_us_address2" text NULL,
  "spons_dfe_loc_us_city" text NULL,
  "spons_dfe_loc_us_state" text NULL,
  "spons_dfe_loc_us_zip" text NULL,
  "spons_dfe_loc_foreign_address1" text NULL,
  "spons_dfe_loc_foreign_address2" text NULL,
  "spons_dfe_loc_foreign_city" text NULL,
  "spons_dfe_loc_forgn_prov_st" text NULL,
  "spons_dfe_loc_foreign_cntry" text NULL,
  "spons_dfe_loc_forgn_postal_cd" text NULL,
  "spons_dfe_ein" text NULL,
  "spons_dfe_phone_num" text NULL,
  "business_code" text NULL,
  "admin_name" text NULL,
  "admin_care_of_name" text NULL,
  "admin_us_address1" text NULL,
  "admin_us_address2" text NULL,
  "admin_us_city" text NULL,
  "admin_us_state" text NULL,
  "admin_us_zip" text NULL,
  "admin_foreign_address1" text NULL,
  "admin_foreign_address2" text NULL,
  "admin_foreign_city" text NULL,
  "admin_foreign_prov_state" text NULL,
  "admin_foreign_cntry" text NULL,
  "admin_foreign_postal_cd" text NULL,
  "admin_ein" text NULL,
  "admin_phone_num" text NULL,
  "last_rpt_spons_name" text NULL,
  "last_rpt_spons_ein" text NULL,
  "last_rpt_plan_num" text NULL,
  "admin_signed_date" text NULL,
  "admin_signed_name" text NULL,
  "spons_signed_date" text NULL,
  "spons_signed_name" text NULL,
  "dfe_signed_date" text NULL,
  "dfe_signed_name" text NULL,
  "tot_partcp_boy_cnt" integer NULL,
  "tot_active_partcp_cnt" integer NULL,
  "rtd_sep_partcp_rcvg_cnt" integer NULL,
  "rtd_sep_partcp_fut_cnt" integer NULL,
  "subtl_act_rtd_sep_cnt" integer NULL,
  "benef_rcvg_bnft_cnt" integer NULL,
  "tot_act_rtd_sep_benef_cnt" integer NULL,
  "partcp_account_bal_cnt" integer NULL,
  "sep_partcp_partl_vstd_cnt" integer NULL,
  "contrib_emplrs_cnt" integer NULL,
  "type_pension_bnft_code" text NULL,
  "type_welfare_bnft_code" text NULL,
  "funding_insurance_ind" text NULL,
  "funding_sec412_ind" text NULL,
  "funding_trust_ind" text NULL,
  "funding_gen_asset_ind" text NULL,
  "benefit_insurance_ind" text NULL,
  "benefit_sec412_ind" text NULL,
  "benefit_trust_ind" text NULL,
  "benefit_gen_asset_ind" text NULL,
  "sch_r_attached_ind" text NULL,
  "sch_mb_attached_ind" text NULL,
  "sch_sb_attached_ind" text NULL,
  "sch_h_attached_ind" text NULL,
  "sch_i_attached_ind" text NULL,
  "sch_a_attached_ind" text NULL,
  "num_sch_a_attached_cnt" integer NULL,
  "sch_c_attached_ind" text NULL,
  "sch_d_attached_ind" text NULL,
  "sch_g_attached_ind" text NULL,
  "filing_status" text NULL,
  "date_received" text NULL,
  "valid_admin_signature" text NULL,
  "valid_dfe_signature" text NULL,
  "valid_sponsor_signature" text NULL,
  "admin_phone_num_foreign" text NULL,
  "spons_dfe_phone_num_foreign" text NULL,
  "admin_name_same_spon_ind" text NULL,
  "admin_address_same_spon_ind" text NULL,
  "preparer_name" text NULL,
  "preparer_firm_name" text NULL,
  "preparer_us_address1" text NULL,
  "preparer_us_address2" text NULL,
  "preparer_us_city" text NULL,
  "preparer_us_state" text NULL,
  "preparer_us_zip" text NULL,
  "preparer_foreign_address1" text NULL,
  "preparer_foreign_address2" text NULL,
  "preparer_foreign_city" text NULL,
  "preparer_foreign_prov_state" text NULL,
  "preparer_foreign_cntry" text NULL,
  "preparer_foreign_postal_cd" text NULL,
  "preparer_phone_num" text NULL,
  "preparer_phone_num_foreign" text NULL,
  "tot_act_partcp_boy_cnt" integer NULL,
  "subj_m1_filing_req_ind" text NULL,
  "compliance_m1_filing_req_ind" text NULL,
  "m1_receipt_confirmation_code" text NULL,
  "admin_manual_signed_date" text NULL,
  "admin_manual_signed_name" text NULL,
  "last_rpt_plan_name" text NULL,
  "spons_manual_signed_date" text NULL,
  "spons_manual_signed_name" text NULL,
  "dfe_manual_signed_date" text NULL,
  "dfe_manual_signed_name" text NULL,
  "adopted_plan_perm_sec_act" text NULL,
  "partcp_account_bal_cnt_boy" integer NULL,
  "sch_dcg_attached_ind" text NULL,
  "num_sch_dcg_attached_cnt" integer NULL,
  "sch_mep_attached_ind" text NULL,
  PRIMARY KEY ("ack_id")
);
-- Create index "idx_f5500_ein" to table: "form_5500"
CREATE INDEX "idx_f5500_ein" ON "fed_data"."form_5500" ("spons_dfe_ein");
-- Create index "idx_f5500_plan_year" to table: "form_5500"
CREATE INDEX "idx_f5500_plan_year" ON "fed_data"."form_5500" ("form_plan_year_begin_date");
-- Create index "idx_f5500_sponsor_trgm" to table: "form_5500"
CREATE INDEX "idx_f5500_sponsor_trgm" ON "fed_data"."form_5500" USING GIN ("sponsor_dfe_name" public.gin_trgm_ops);
-- Create index "idx_f5500_sponsor_upper" to table: "form_5500"
CREATE INDEX "idx_f5500_sponsor_upper" ON "fed_data"."form_5500" ((upper(TRIM(BOTH FROM sponsor_dfe_name))));

-- Create "form_5500_providers" table
CREATE TABLE "fed_data"."form_5500_providers" (
  "ack_id" text NOT NULL,
  "row_order" integer NOT NULL,
  "provider_eligible_name" text NULL,
  "provider_eligible_ein" text NULL,
  "provider_eligible_us_address1" text NULL,
  "provider_eligible_us_address2" text NULL,
  "provider_eligible_us_city" text NULL,
  "provider_eligible_us_state" text NULL,
  "provider_eligible_us_zip" text NULL,
  "prov_eligible_foreign_address1" text NULL,
  "prov_eligible_foreign_address2" text NULL,
  "prov_eligible_foreign_city" text NULL,
  "prov_eligible_foreign_prov_st" text NULL,
  "prov_eligible_foreign_cntry" text NULL,
  "prov_eligible_foreign_post_cd" text NULL,
  PRIMARY KEY ("ack_id", "row_order")
);
-- Create index "idx_f5500prov_ein" to table: "form_5500_providers"
CREATE INDEX "idx_f5500prov_ein" ON "fed_data"."form_5500_providers" ("provider_eligible_ein");
-- Create index "idx_f5500prov_name_trgm" to table: "form_5500_providers"
CREATE INDEX "idx_f5500prov_name_trgm" ON "fed_data"."form_5500_providers" USING GIN ("provider_eligible_name" public.gin_trgm_ops);

-- Create "form_5500_schedule_h" table
CREATE TABLE "fed_data"."form_5500_schedule_h" (
  "ack_id" text NOT NULL,
  "sch_h_plan_year_begin_date" text NULL,
  "sch_h_tax_prd" text NULL,
  "sch_h_pn" text NULL,
  "sch_h_ein" text NULL,
  "non_int_bear_cash_boy_amt" numeric NULL,
  "emplr_contrib_boy_amt" numeric NULL,
  "partcp_contrib_boy_amt" numeric NULL,
  "other_receivables_boy_amt" numeric NULL,
  "int_bear_cash_boy_amt" numeric NULL,
  "govt_sec_boy_amt" numeric NULL,
  "corp_debt_preferred_boy_amt" numeric NULL,
  "corp_debt_other_boy_amt" numeric NULL,
  "pref_stock_boy_amt" numeric NULL,
  "common_stock_boy_amt" numeric NULL,
  "joint_venture_boy_amt" numeric NULL,
  "real_estate_boy_amt" numeric NULL,
  "other_loans_boy_amt" numeric NULL,
  "partcp_loans_boy_amt" numeric NULL,
  "int_common_tr_boy_amt" numeric NULL,
  "int_pool_sep_acct_boy_amt" numeric NULL,
  "int_master_tr_boy_amt" numeric NULL,
  "int_103_12_invst_boy_amt" numeric NULL,
  "int_reg_invst_co_boy_amt" numeric NULL,
  "ins_co_gen_acct_boy_amt" numeric NULL,
  "oth_invst_boy_amt" numeric NULL,
  "emplr_sec_boy_amt" numeric NULL,
  "emplr_prop_boy_amt" numeric NULL,
  "bldgs_used_boy_amt" numeric NULL,
  "tot_assets_boy_amt" numeric NULL,
  "bnfts_payable_boy_amt" numeric NULL,
  "oprtng_payable_boy_amt" numeric NULL,
  "acquis_indbt_boy_amt" numeric NULL,
  "other_liab_boy_amt" numeric NULL,
  "tot_liabilities_boy_amt" numeric NULL,
  "net_assets_boy_amt" numeric NULL,
  "non_int_bear_cash_eoy_amt" numeric NULL,
  "emplr_contrib_eoy_amt" numeric NULL,
  "partcp_contrib_eoy_amt" numeric NULL,
  "other_receivables_eoy_amt" numeric NULL,
  "int_bear_cash_eoy_amt" numeric NULL,
  "govt_sec_eoy_amt" numeric NULL,
  "corp_debt_preferred_eoy_amt" numeric NULL,
  "corp_debt_other_eoy_amt" numeric NULL,
  "pref_stock_eoy_amt" numeric NULL,
  "common_stock_eoy_amt" numeric NULL,
  "joint_venture_eoy_amt" numeric NULL,
  "real_estate_eoy_amt" numeric NULL,
  "other_loans_eoy_amt" numeric NULL,
  "partcp_loans_eoy_amt" numeric NULL,
  "int_common_tr_eoy_amt" numeric NULL,
  "int_pool_sep_acct_eoy_amt" numeric NULL,
  "int_master_tr_eoy_amt" numeric NULL,
  "int_103_12_invst_eoy_amt" numeric NULL,
  "int_reg_invst_co_eoy_amt" numeric NULL,
  "ins_co_gen_acct_eoy_amt" numeric NULL,
  "oth_invst_eoy_amt" numeric NULL,
  "emplr_sec_eoy_amt" numeric NULL,
  "emplr_prop_eoy_amt" numeric NULL,
  "bldgs_used_eoy_amt" numeric NULL,
  "tot_assets_eoy_amt" numeric NULL,
  "bnfts_payable_eoy_amt" numeric NULL,
  "oprtng_payable_eoy_amt" numeric NULL,
  "acquis_indbt_eoy_amt" numeric NULL,
  "other_liab_eoy_amt" numeric NULL,
  "tot_liabilities_eoy_amt" numeric NULL,
  "net_assets_eoy_amt" numeric NULL,
  "emplr_contrib_income_amt" numeric NULL,
  "participant_contrib_amt" numeric NULL,
  "oth_contrib_rcvd_amt" numeric NULL,
  "non_cash_contrib_bs_amt" numeric NULL,
  "tot_contrib_amt" numeric NULL,
  "int_bear_cash_amt" numeric NULL,
  "int_on_govt_sec_amt" numeric NULL,
  "int_on_corp_debt_amt" numeric NULL,
  "int_on_oth_loans_amt" numeric NULL,
  "int_on_partcp_loans_amt" numeric NULL,
  "int_on_oth_invst_amt" numeric NULL,
  "total_interest_amt" numeric NULL,
  "divnd_pref_stock_amt" numeric NULL,
  "divnd_common_stock_amt" numeric NULL,
  "registered_invst_amt" numeric NULL,
  "total_dividends_amt" numeric NULL,
  "total_rents_amt" numeric NULL,
  "aggregate_proceeds_amt" numeric NULL,
  "aggregate_costs_amt" numeric NULL,
  "tot_gain_loss_sale_ast_amt" numeric NULL,
  "unrealzd_apprctn_re_amt" numeric NULL,
  "unrealzd_apprctn_oth_amt" numeric NULL,
  "tot_unrealzd_apprctn_amt" numeric NULL,
  "gain_loss_com_trust_amt" numeric NULL,
  "gain_loss_pool_sep_amt" numeric NULL,
  "gain_loss_master_tr_amt" numeric NULL,
  "gain_loss_103_12_invst_amt" numeric NULL,
  "gain_loss_reg_invst_amt" numeric NULL,
  "other_income_amt" numeric NULL,
  "tot_income_amt" numeric NULL,
  "distrib_drt_partcp_amt" numeric NULL,
  "ins_carrier_bnfts_amt" numeric NULL,
  "oth_bnft_payment_amt" numeric NULL,
  "tot_distrib_bnft_amt" numeric NULL,
  "tot_corrective_distrib_amt" numeric NULL,
  "tot_deemed_distr_part_lns_amt" numeric NULL,
  "tot_int_expense_amt" numeric NULL,
  "professional_fees_amt" numeric NULL,
  "contract_admin_fees_amt" numeric NULL,
  "invst_mgmt_fees_amt" numeric NULL,
  "other_admin_fees_amt" numeric NULL,
  "tot_admin_expenses_amt" numeric NULL,
  "tot_expenses_amt" numeric NULL,
  "net_income_amt" numeric NULL,
  "tot_transfers_to_amt" numeric NULL,
  "tot_transfers_from_amt" numeric NULL,
  "acctnt_opinion_type_cd" text NULL,
  "acct_performed_ltd_audit_ind" text NULL,
  "accountant_firm_name" text NULL,
  "accountant_firm_ein" text NULL,
  "acct_opin_not_on_file_ind" text NULL,
  "fail_transmit_contrib_ind" text NULL,
  "fail_transmit_contrib_amt" numeric NULL,
  "loans_in_default_ind" text NULL,
  "loans_in_default_amt" numeric NULL,
  "leases_in_default_ind" text NULL,
  "leases_in_default_amt" numeric NULL,
  "party_in_int_not_rptd_ind" text NULL,
  "party_in_int_not_rptd_amt" numeric NULL,
  "plan_ins_fdlty_bond_ind" text NULL,
  "plan_ins_fdlty_bond_amt" numeric NULL,
  "loss_discv_dur_year_ind" text NULL,
  "loss_discv_dur_year_amt" numeric NULL,
  "asset_undeterm_val_ind" text NULL,
  "asset_undeterm_val_amt" numeric NULL,
  "non_cash_contrib_ind" text NULL,
  "non_cash_contrib_amt" numeric NULL,
  "ast_held_invst_ind" text NULL,
  "five_prcnt_trans_ind" text NULL,
  "all_plan_ast_distrib_ind" text NULL,
  "fail_provide_benefit_due_ind" text NULL,
  "fail_provide_benefit_due_amt" numeric NULL,
  "plan_blackout_period_ind" text NULL,
  "comply_blackout_notice_ind" text NULL,
  "res_term_plan_adpt_ind" text NULL,
  "res_term_plan_adpt_amt" numeric NULL,
  "fdcry_trust_ein" text NULL,
  "fdcry_trust_name" text NULL,
  "covered_pbgc_insurance_ind" text NULL,
  "trust_incur_unrel_tax_inc_ind" text NULL,
  "trust_incur_unrel_tax_inc_amt" numeric NULL,
  "in_service_distrib_ind" text NULL,
  "in_service_distrib_amt" numeric NULL,
  "fdcry_trustee_cust_name" text NULL,
  "fdcry_trust_cust_phon_num" text NULL,
  "fdcry_trust_cust_phon_nu_fore" text NULL,
  "distrib_made_employee_62_ind" text NULL,
  "premium_filing_confirm_number" text NULL,
  "acct_perf_ltd_audit_103_8_ind" text NULL,
  "acct_perf_ltd_audit_103_12_ind" text NULL,
  "acct_perf_not_ltd_audit_ind" text NULL,
  "salaries_allowances_amt" numeric NULL,
  "oth_recordkeeping_fees_amt" numeric NULL,
  "iqpa_audit_fees_amt" numeric NULL,
  "trustee_custodial_fees_amt" numeric NULL,
  "actuarial_fees_amt" numeric NULL,
  "legal_fees_amt" numeric NULL,
  "valuation_appraisal_fees_amt" numeric NULL,
  "other_trustee_fees_expenses_amt" numeric NULL,
  PRIMARY KEY ("ack_id")
);
-- Create index "idx_f5500sch_h_ein" to table: "form_5500_schedule_h"
CREATE INDEX "idx_f5500sch_h_ein" ON "fed_data"."form_5500_schedule_h" ("sch_h_ein");
-- Create index "idx_f5500sch_h_tot_assets" to table: "form_5500_schedule_h"
CREATE INDEX "idx_f5500sch_h_tot_assets" ON "fed_data"."form_5500_schedule_h" ("tot_assets_eoy_amt");

-- Create "form_5500_sf" table
CREATE TABLE "fed_data"."form_5500_sf" (
  "ack_id" text NOT NULL,
  "sf_plan_year_begin_date" text NULL,
  "sf_tax_prd" text NULL,
  "sf_plan_entity_cd" text NULL,
  "sf_initial_filing_ind" text NULL,
  "sf_amended_ind" text NULL,
  "sf_final_filing_ind" text NULL,
  "sf_short_plan_yr_ind" text NULL,
  "sf_5558_application_filed_ind" text NULL,
  "sf_ext_automatic_ind" text NULL,
  "sf_dfvc_program_ind" text NULL,
  "sf_ext_special_ind" text NULL,
  "sf_ext_special_text" text NULL,
  "sf_plan_name" text NULL,
  "sf_plan_num" text NULL,
  "sf_plan_eff_date" text NULL,
  "sf_sponsor_name" text NULL,
  "sf_sponsor_dfe_dba_name" text NULL,
  "sf_spons_us_address1" text NULL,
  "sf_spons_us_address2" text NULL,
  "sf_spons_us_city" text NULL,
  "sf_spons_us_state" text NULL,
  "sf_spons_us_zip" text NULL,
  "sf_spons_foreign_address1" text NULL,
  "sf_spons_foreign_address2" text NULL,
  "sf_spons_foreign_city" text NULL,
  "sf_spons_foreign_prov_state" text NULL,
  "sf_spons_foreign_cntry" text NULL,
  "sf_spons_foreign_postal_cd" text NULL,
  "sf_spons_ein" text NULL,
  "sf_spons_phone_num" text NULL,
  "sf_business_code" text NULL,
  "sf_admin_name" text NULL,
  "sf_admin_care_of_name" text NULL,
  "sf_admin_us_address1" text NULL,
  "sf_admin_us_address2" text NULL,
  "sf_admin_us_city" text NULL,
  "sf_admin_us_state" text NULL,
  "sf_admin_us_zip" text NULL,
  "sf_admin_foreign_address1" text NULL,
  "sf_admin_foreign_address2" text NULL,
  "sf_admin_foreign_city" text NULL,
  "sf_admin_foreign_prov_state" text NULL,
  "sf_admin_foreign_cntry" text NULL,
  "sf_admin_foreign_postal_cd" text NULL,
  "sf_admin_ein" text NULL,
  "sf_admin_phone_num" text NULL,
  "sf_last_rpt_spons_name" text NULL,
  "sf_last_rpt_spons_ein" text NULL,
  "sf_last_rpt_plan_num" text NULL,
  "sf_tot_partcp_boy_cnt" integer NULL,
  "sf_tot_act_rtd_sep_benef_cnt" integer NULL,
  "sf_partcp_account_bal_cnt" integer NULL,
  "sf_eligible_assets_ind" text NULL,
  "sf_iqpa_waiver_ind" text NULL,
  "sf_tot_assets_boy_amt" numeric NULL,
  "sf_tot_liabilities_boy_amt" numeric NULL,
  "sf_net_assets_boy_amt" numeric NULL,
  "sf_tot_assets_eoy_amt" numeric NULL,
  "sf_tot_liabilities_eoy_amt" numeric NULL,
  "sf_net_assets_eoy_amt" numeric NULL,
  "sf_emplr_contrib_income_amt" numeric NULL,
  "sf_particip_contrib_income_amt" numeric NULL,
  "sf_oth_contrib_rcvd_amt" numeric NULL,
  "sf_other_income_amt" numeric NULL,
  "sf_tot_income_amt" numeric NULL,
  "sf_tot_distrib_bnft_amt" numeric NULL,
  "sf_corrective_deemed_distr_amt" numeric NULL,
  "sf_admin_srvc_providers_amt" numeric NULL,
  "sf_oth_expenses_amt" numeric NULL,
  "sf_tot_expenses_amt" numeric NULL,
  "sf_net_income_amt" numeric NULL,
  "sf_tot_plan_transfers_amt" numeric NULL,
  "sf_type_pension_bnft_code" text NULL,
  "sf_type_welfare_bnft_code" text NULL,
  "sf_fail_transmit_contrib_ind" text NULL,
  "sf_fail_transmit_contrib_amt" numeric NULL,
  "sf_party_in_int_not_rptd_ind" text NULL,
  "sf_party_in_int_not_rptd_amt" numeric NULL,
  "sf_plan_ins_fdlty_bond_ind" text NULL,
  "sf_plan_ins_fdlty_bond_amt" numeric NULL,
  "sf_loss_discv_dur_year_ind" text NULL,
  "sf_loss_discv_dur_year_amt" numeric NULL,
  "sf_broker_fees_paid_ind" text NULL,
  "sf_broker_fees_paid_amt" numeric NULL,
  "sf_fail_provide_benef_due_ind" text NULL,
  "sf_fail_provide_benef_due_amt" numeric NULL,
  "sf_partcp_loans_ind" text NULL,
  "sf_partcp_loans_eoy_amt" numeric NULL,
  "sf_plan_blackout_period_ind" text NULL,
  "sf_comply_blackout_notice_ind" text NULL,
  "sf_db_plan_funding_reqd_ind" text NULL,
  "sf_dc_plan_funding_reqd_ind" text NULL,
  "sf_ruling_letter_grant_date" text NULL,
  "sf_sec_412_req_contrib_amt" numeric NULL,
  "sf_emplr_contrib_paid_amt" numeric NULL,
  "sf_funding_deficiency_amt" numeric NULL,
  "sf_funding_deadline_ind" text NULL,
  "sf_res_term_plan_adpt_ind" text NULL,
  "sf_res_term_plan_adpt_amt" numeric NULL,
  "sf_all_plan_ast_distrib_ind" text NULL,
  "sf_admin_signed_date" text NULL,
  "sf_admin_signed_name" text NULL,
  "sf_spons_signed_date" text NULL,
  "sf_spons_signed_name" text NULL,
  "filing_status" text NULL,
  "date_received" text NULL,
  "valid_admin_signature" text NULL,
  "valid_sponsor_signature" text NULL,
  "sf_admin_phone_num_foreign" text NULL,
  "sf_spons_care_of_name" text NULL,
  "sf_spons_loc_foreign_address1" text NULL,
  "sf_spons_loc_foreign_address2" text NULL,
  "sf_spons_loc_foreign_city" text NULL,
  "sf_spons_loc_foreign_cntry" text NULL,
  "sf_spons_loc_foreign_postal_cd" text NULL,
  "sf_spons_loc_foreign_prov_stat" text NULL,
  "sf_spons_loc_us_address1" text NULL,
  "sf_spons_loc_us_address2" text NULL,
  "sf_spons_loc_us_city" text NULL,
  "sf_spons_loc_us_state" text NULL,
  "sf_spons_loc_us_zip" text NULL,
  "sf_spons_phone_num_foreign" text NULL,
  "sf_admin_name_same_spon_ind" text NULL,
  "sf_admin_addrss_same_spon_ind" text NULL,
  "sf_preparer_name" text NULL,
  "sf_preparer_firm_name" text NULL,
  "sf_preparer_us_address1" text NULL,
  "sf_preparer_us_address2" text NULL,
  "sf_preparer_us_city" text NULL,
  "sf_preparer_us_state" text NULL,
  "sf_preparer_us_zip" text NULL,
  "sf_preparer_foreign_address1" text NULL,
  "sf_preparer_foreign_address2" text NULL,
  "sf_preparer_foreign_city" text NULL,
  "sf_preparer_foreign_prov_state" text NULL,
  "sf_preparer_foreign_cntry" text NULL,
  "sf_preparer_foreign_postal_cd" text NULL,
  "sf_preparer_phone_num" text NULL,
  "sf_preparer_phone_num_foreign" text NULL,
  "sf_fdcry_trust_name" text NULL,
  "sf_fdcry_trust_ein" text NULL,
  "sf_unp_min_cont_cur_yrtot_amt" numeric NULL,
  "sf_covered_pbgc_insurance_ind" text NULL,
  "sf_tot_act_partcp_boy_cnt" integer NULL,
  "sf_tot_act_partcp_eoy_cnt" integer NULL,
  "sf_sep_partcp_partl_vstd_cnt" integer NULL,
  "sf_trus_inc_unrel_tax_inc_ind" text NULL,
  "sf_trus_inc_unrel_tax_inc_amt" numeric NULL,
  "sf_fdcry_truste_cust_name" text NULL,
  "sf_fdcry_truste_cust_phone_num" text NULL,
  "sf_fdcry_trus_cus_phon_numfore" text NULL,
  "sf_401k_plan_ind" text NULL,
  "sf_401k_satisfy_rqmts_ind" text NULL,
  "sf_adp_acp_test_ind" text NULL,
  "sf_mthd_used_satisfy_rqmts_ind" text NULL,
  "sf_plan_satisfy_tests_ind" text NULL,
  "sf_plan_timely_amended_ind" text NULL,
  "sf_last_plan_amendment_date" text NULL,
  "sf_tax_code" text NULL,
  "sf_last_opin_advi_date" text NULL,
  "sf_last_opin_advi_serial_num" text NULL,
  "sf_fav_determ_ltr_date" text NULL,
  "sf_plan_maintain_us_terri_ind" text NULL,
  "sf_in_service_distrib_ind" text NULL,
  "sf_in_service_distrib_amt" numeric NULL,
  "sf_min_req_distrib_ind" text NULL,
  "sf_admin_manual_sign_date" text NULL,
  "sf_admin_manual_signed_name" text NULL,
  "sf_401k_design_based_safe_ind" text NULL,
  "sf_401k_prior_year_adp_ind" text NULL,
  "sf_401k_current_year_adp_ind" text NULL,
  "sf_401k_na_ind" text NULL,
  "sf_mthd_ratio_prcnt_test_ind" text NULL,
  "sf_mthd_avg_bnft_test_ind" text NULL,
  "sf_mthd_na_ind" text NULL,
  "sf_distrib_made_employe_62_ind" text NULL,
  "sf_last_rpt_plan_name" text NULL,
  "sf_premium_filing_confirm_no" text NULL,
  "sf_spons_manual_signed_date" text NULL,
  "sf_spons_manual_signed_name" text NULL,
  "sf_pbgc_notified_cd" text NULL,
  "sf_pbgc_notified_explan_text" text NULL,
  "sf_adopted_plan_perm_sec_act" text NULL,
  "collectively_bargained" text NULL,
  "sf_partcp_account_bal_cnt_boy" integer NULL,
  "sf_401k_design_based_safe_harbor_ind" text NULL,
  "sf_401k_prior_year_adp_test_ind" text NULL,
  "sf_401k_current_year_adp_test_ind" text NULL,
  "sf_opin_letter_date" text NULL,
  "sf_opin_letter_serial_num" text NULL,
  PRIMARY KEY ("ack_id")
);
-- Create index "idx_f5500sf_ein" to table: "form_5500_sf"
CREATE INDEX "idx_f5500sf_ein" ON "fed_data"."form_5500_sf" ("sf_spons_ein");
-- Create index "idx_f5500sf_plan_year" to table: "form_5500_sf"
CREATE INDEX "idx_f5500sf_plan_year" ON "fed_data"."form_5500_sf" ("sf_plan_year_begin_date");
-- Create index "idx_f5500sf_sponsor_trgm" to table: "form_5500_sf"
CREATE INDEX "idx_f5500sf_sponsor_trgm" ON "fed_data"."form_5500_sf" USING GIN ("sf_sponsor_name" public.gin_trgm_ops);

-- Create "eo_bmf" table
CREATE TABLE "fed_data"."eo_bmf" (
  "ein" text NOT NULL,
  "name" text NOT NULL,
  "ico" text NULL,
  "street" text NULL,
  "city" text NULL,
  "state" text NULL,
  "zip" text NULL,
  "group_exemption" text NULL,
  "subsection" smallint NULL,
  "affiliation" smallint NULL,
  "classification" text NULL,
  "ruling" text NULL,
  "deductibility" smallint NULL,
  "foundation" smallint NULL,
  "activity" text NULL,
  "organization" smallint NULL,
  "status" smallint NULL,
  "tax_period" text NULL,
  "asset_cd" smallint NULL,
  "income_cd" smallint NULL,
  "filing_req_cd" smallint NULL,
  "pf_filing_req_cd" smallint NULL,
  "acct_pd" smallint NULL,
  "asset_amt" bigint NULL,
  "income_amt" bigint NULL,
  "revenue_amt" bigint NULL,
  "ntee_cd" text NULL,
  "sort_name" text NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("ein")
);
-- Create index "idx_eo_bmf_asset_amt" to table: "eo_bmf"
CREATE INDEX "idx_eo_bmf_asset_amt" ON "fed_data"."eo_bmf" ("asset_amt" DESC NULLS LAST);
-- Create index "idx_eo_bmf_name_trgm" to table: "eo_bmf"
CREATE INDEX "idx_eo_bmf_name_trgm" ON "fed_data"."eo_bmf" USING GIN ("name" public.gin_trgm_ops);
-- Create index "idx_eo_bmf_ntee" to table: "eo_bmf"
CREATE INDEX "idx_eo_bmf_ntee" ON "fed_data"."eo_bmf" ("ntee_cd");
-- Create index "idx_eo_bmf_state" to table: "eo_bmf"
CREATE INDEX "idx_eo_bmf_state" ON "fed_data"."eo_bmf" ("state");
-- Create index "idx_eo_bmf_subsection" to table: "eo_bmf"
CREATE INDEX "idx_eo_bmf_subsection" ON "fed_data"."eo_bmf" ("subsection");
