// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	scrape "github.com/sells-group/research-cli/internal/scrape"
	mock "github.com/stretchr/testify/mock"
)

// MockScraper is an autogenerated mock type for the Scraper type
type MockScraper struct {
	mock.Mock
}

type MockScraper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScraper) EXPECT() *MockScraper_Expecter {
	return &MockScraper_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *MockScraper) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockScraper_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockScraper_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockScraper_Expecter) Name() *MockScraper_Name_Call {
	return &MockScraper_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockScraper_Name_Call) Run(run func()) *MockScraper_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScraper_Name_Call) Return(_a0 string) *MockScraper_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScraper_Name_Call) RunAndReturn(run func() string) *MockScraper_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Scrape provides a mock function with given fields: ctx, url
func (_m *MockScraper) Scrape(ctx context.Context, url string) (*scrape.Result, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Scrape")
	}

	var r0 *scrape.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*scrape.Result, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *scrape.Result); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*scrape.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScraper_Scrape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scrape'
type MockScraper_Scrape_Call struct {
	*mock.Call
}

// Scrape is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockScraper_Expecter) Scrape(ctx interface{}, url interface{}) *MockScraper_Scrape_Call {
	return &MockScraper_Scrape_Call{Call: _e.mock.On("Scrape", ctx, url)}
}

func (_c *MockScraper_Scrape_Call) Run(run func(ctx context.Context, url string)) *MockScraper_Scrape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockScraper_Scrape_Call) Return(_a0 *scrape.Result, _a1 error) *MockScraper_Scrape_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScraper_Scrape_Call) RunAndReturn(run func(context.Context, string) (*scrape.Result, error)) *MockScraper_Scrape_Call {
	_c.Call.Return(run)
	return _c
}

// Supports provides a mock function with given fields: url
func (_m *MockScraper) Supports(url string) bool {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Supports")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockScraper_Supports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Supports'
type MockScraper_Supports_Call struct {
	*mock.Call
}

// Supports is a helper method to define mock.On call
//   - url string
func (_e *MockScraper_Expecter) Supports(url interface{}) *MockScraper_Supports_Call {
	return &MockScraper_Supports_Call{Call: _e.mock.On("Supports", url)}
}

func (_c *MockScraper_Supports_Call) Run(run func(url string)) *MockScraper_Supports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockScraper_Supports_Call) Return(_a0 bool) *MockScraper_Supports_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScraper_Supports_Call) RunAndReturn(run func(string) bool) *MockScraper_Supports_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScraper creates a new instance of MockScraper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScraper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScraper {
	mock := &MockScraper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
