// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	perplexity "github.com/sells-group/research-cli/pkg/perplexity"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// ChatCompletion provides a mock function with given fields: ctx, req
func (_m *MockClient) ChatCompletion(ctx context.Context, req perplexity.ChatCompletionRequest) (*perplexity.ChatCompletionResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ChatCompletion")
	}

	var r0 *perplexity.ChatCompletionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, perplexity.ChatCompletionRequest) (*perplexity.ChatCompletionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, perplexity.ChatCompletionRequest) *perplexity.ChatCompletionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*perplexity.ChatCompletionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, perplexity.ChatCompletionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ChatCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatCompletion'
type MockClient_ChatCompletion_Call struct {
	*mock.Call
}

// ChatCompletion is a helper method to define mock.On call
//   - ctx context.Context
//   - req perplexity.ChatCompletionRequest
func (_e *MockClient_Expecter) ChatCompletion(ctx interface{}, req interface{}) *MockClient_ChatCompletion_Call {
	return &MockClient_ChatCompletion_Call{Call: _e.mock.On("ChatCompletion", ctx, req)}
}

func (_c *MockClient_ChatCompletion_Call) Run(run func(ctx context.Context, req perplexity.ChatCompletionRequest)) *MockClient_ChatCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(perplexity.ChatCompletionRequest))
	})
	return _c
}

func (_c *MockClient_ChatCompletion_Call) Return(_a0 *perplexity.ChatCompletionResponse, _a1 error) *MockClient_ChatCompletion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ChatCompletion_Call) RunAndReturn(run func(context.Context, perplexity.ChatCompletionRequest) (*perplexity.ChatCompletionResponse, error)) *MockClient_ChatCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
