// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	ppp "github.com/sells-group/research-cli/pkg/ppp"
	mock "github.com/stretchr/testify/mock"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockQuerier) Close() {
	_m.Called()
}

// MockQuerier_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockQuerier_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockQuerier_Expecter) Close() *MockQuerier_Close_Call {
	return &MockQuerier_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockQuerier_Close_Call) Run(run func()) *MockQuerier_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuerier_Close_Call) Return() *MockQuerier_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQuerier_Close_Call) RunAndReturn(run func()) *MockQuerier_Close_Call {
	_c.Run(run)
	return _c
}

// FindLoans provides a mock function with given fields: ctx, name, state, city
func (_m *MockQuerier) FindLoans(ctx context.Context, name string, state string, city string) ([]ppp.LoanMatch, error) {
	ret := _m.Called(ctx, name, state, city)

	if len(ret) == 0 {
		panic("no return value specified for FindLoans")
	}

	var r0 []ppp.LoanMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]ppp.LoanMatch, error)); ok {
		return rf(ctx, name, state, city)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []ppp.LoanMatch); ok {
		r0 = rf(ctx, name, state, city)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ppp.LoanMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, name, state, city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_FindLoans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLoans'
type MockQuerier_FindLoans_Call struct {
	*mock.Call
}

// FindLoans is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - state string
//   - city string
func (_e *MockQuerier_Expecter) FindLoans(ctx interface{}, name interface{}, state interface{}, city interface{}) *MockQuerier_FindLoans_Call {
	return &MockQuerier_FindLoans_Call{Call: _e.mock.On("FindLoans", ctx, name, state, city)}
}

func (_c *MockQuerier_FindLoans_Call) Run(run func(ctx context.Context, name string, state string, city string)) *MockQuerier_FindLoans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockQuerier_FindLoans_Call) Return(_a0 []ppp.LoanMatch, _a1 error) *MockQuerier_FindLoans_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_FindLoans_Call) RunAndReturn(run func(context.Context, string, string, string) ([]ppp.LoanMatch, error)) *MockQuerier_FindLoans_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
