// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: ctx, url
func (_m *MockFetcher) Download(ctx context.Context, url string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFetcher_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockFetcher_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockFetcher_Expecter) Download(ctx interface{}, url interface{}) *MockFetcher_Download_Call {
	return &MockFetcher_Download_Call{Call: _e.mock.On("Download", ctx, url)}
}

func (_c *MockFetcher_Download_Call) Run(run func(ctx context.Context, url string)) *MockFetcher_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFetcher_Download_Call) Return(_a0 io.ReadCloser, _a1 error) *MockFetcher_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFetcher_Download_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockFetcher_Download_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadIfChanged provides a mock function with given fields: ctx, url, etag
func (_m *MockFetcher) DownloadIfChanged(ctx context.Context, url string, etag string) (io.ReadCloser, string, bool, error) {
	ret := _m.Called(ctx, url, etag)

	if len(ret) == 0 {
		panic("no return value specified for DownloadIfChanged")
	}

	var r0 io.ReadCloser
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (io.ReadCloser, string, bool, error)); ok {
		return rf(ctx, url, etag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) io.ReadCloser); ok {
		r0 = rf(ctx, url, etag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, url, etag)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) bool); ok {
		r2 = rf(ctx, url, etag)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = rf(ctx, url, etag)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockFetcher_DownloadIfChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadIfChanged'
type MockFetcher_DownloadIfChanged_Call struct {
	*mock.Call
}

// DownloadIfChanged is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - etag string
func (_e *MockFetcher_Expecter) DownloadIfChanged(ctx interface{}, url interface{}, etag interface{}) *MockFetcher_DownloadIfChanged_Call {
	return &MockFetcher_DownloadIfChanged_Call{Call: _e.mock.On("DownloadIfChanged", ctx, url, etag)}
}

func (_c *MockFetcher_DownloadIfChanged_Call) Run(run func(ctx context.Context, url string, etag string)) *MockFetcher_DownloadIfChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFetcher_DownloadIfChanged_Call) Return(_a0 io.ReadCloser, _a1 string, _a2 bool, _a3 error) *MockFetcher_DownloadIfChanged_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockFetcher_DownloadIfChanged_Call) RunAndReturn(run func(context.Context, string, string) (io.ReadCloser, string, bool, error)) *MockFetcher_DownloadIfChanged_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadToFile provides a mock function with given fields: ctx, url, path
func (_m *MockFetcher) DownloadToFile(ctx context.Context, url string, path string) (int64, error) {
	ret := _m.Called(ctx, url, path)

	if len(ret) == 0 {
		panic("no return value specified for DownloadToFile")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, url, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, url, path)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, url, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFetcher_DownloadToFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadToFile'
type MockFetcher_DownloadToFile_Call struct {
	*mock.Call
}

// DownloadToFile is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - path string
func (_e *MockFetcher_Expecter) DownloadToFile(ctx interface{}, url interface{}, path interface{}) *MockFetcher_DownloadToFile_Call {
	return &MockFetcher_DownloadToFile_Call{Call: _e.mock.On("DownloadToFile", ctx, url, path)}
}

func (_c *MockFetcher_DownloadToFile_Call) Run(run func(ctx context.Context, url string, path string)) *MockFetcher_DownloadToFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFetcher_DownloadToFile_Call) Return(_a0 int64, _a1 error) *MockFetcher_DownloadToFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFetcher_DownloadToFile_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *MockFetcher_DownloadToFile_Call {
	_c.Call.Return(run)
	return _c
}

// HeadETag provides a mock function with given fields: ctx, url
func (_m *MockFetcher) HeadETag(ctx context.Context, url string) (string, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for HeadETag")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFetcher_HeadETag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadETag'
type MockFetcher_HeadETag_Call struct {
	*mock.Call
}

// HeadETag is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockFetcher_Expecter) HeadETag(ctx interface{}, url interface{}) *MockFetcher_HeadETag_Call {
	return &MockFetcher_HeadETag_Call{Call: _e.mock.On("HeadETag", ctx, url)}
}

func (_c *MockFetcher_HeadETag_Call) Run(run func(ctx context.Context, url string)) *MockFetcher_HeadETag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFetcher_HeadETag_Call) Return(_a0 string, _a1 error) *MockFetcher_HeadETag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFetcher_HeadETag_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockFetcher_HeadETag_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
