// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	anthropic "github.com/sells-group/research-cli/pkg/anthropic"
	mock "github.com/stretchr/testify/mock"
)

// MockBatchResultIterator is an autogenerated mock type for the BatchResultIterator type
type MockBatchResultIterator struct {
	mock.Mock
}

type MockBatchResultIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchResultIterator) EXPECT() *MockBatchResultIterator_Expecter {
	return &MockBatchResultIterator_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockBatchResultIterator) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBatchResultIterator_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBatchResultIterator_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBatchResultIterator_Expecter) Close() *MockBatchResultIterator_Close_Call {
	return &MockBatchResultIterator_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBatchResultIterator_Close_Call) Run(run func()) *MockBatchResultIterator_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBatchResultIterator_Close_Call) Return(_a0 error) *MockBatchResultIterator_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBatchResultIterator_Close_Call) RunAndReturn(run func() error) *MockBatchResultIterator_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function with no fields
func (_m *MockBatchResultIterator) Err() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBatchResultIterator_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockBatchResultIterator_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockBatchResultIterator_Expecter) Err() *MockBatchResultIterator_Err_Call {
	return &MockBatchResultIterator_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockBatchResultIterator_Err_Call) Run(run func()) *MockBatchResultIterator_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBatchResultIterator_Err_Call) Return(_a0 error) *MockBatchResultIterator_Err_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBatchResultIterator_Err_Call) RunAndReturn(run func() error) *MockBatchResultIterator_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Item provides a mock function with no fields
func (_m *MockBatchResultIterator) Item() anthropic.BatchResultItem {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Item")
	}

	var r0 anthropic.BatchResultItem
	if rf, ok := ret.Get(0).(func() anthropic.BatchResultItem); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(anthropic.BatchResultItem)
	}

	return r0
}

// MockBatchResultIterator_Item_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Item'
type MockBatchResultIterator_Item_Call struct {
	*mock.Call
}

// Item is a helper method to define mock.On call
func (_e *MockBatchResultIterator_Expecter) Item() *MockBatchResultIterator_Item_Call {
	return &MockBatchResultIterator_Item_Call{Call: _e.mock.On("Item")}
}

func (_c *MockBatchResultIterator_Item_Call) Run(run func()) *MockBatchResultIterator_Item_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBatchResultIterator_Item_Call) Return(_a0 anthropic.BatchResultItem) *MockBatchResultIterator_Item_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBatchResultIterator_Item_Call) RunAndReturn(run func() anthropic.BatchResultItem) *MockBatchResultIterator_Item_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with no fields
func (_m *MockBatchResultIterator) Next() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBatchResultIterator_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockBatchResultIterator_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockBatchResultIterator_Expecter) Next() *MockBatchResultIterator_Next_Call {
	return &MockBatchResultIterator_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockBatchResultIterator_Next_Call) Run(run func()) *MockBatchResultIterator_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBatchResultIterator_Next_Call) Return(_a0 bool) *MockBatchResultIterator_Next_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBatchResultIterator_Next_Call) RunAndReturn(run func() bool) *MockBatchResultIterator_Next_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBatchResultIterator creates a new instance of MockBatchResultIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchResultIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchResultIterator {
	mock := &MockBatchResultIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
