// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	anthropic "github.com/sells-group/research-cli/pkg/anthropic"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateBatch provides a mock function with given fields: ctx, req
func (_m *MockClient) CreateBatch(ctx context.Context, req anthropic.BatchRequest) (*anthropic.BatchResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 *anthropic.BatchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, anthropic.BatchRequest) (*anthropic.BatchResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, anthropic.BatchRequest) *anthropic.BatchResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*anthropic.BatchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, anthropic.BatchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockClient_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - req anthropic.BatchRequest
func (_e *MockClient_Expecter) CreateBatch(ctx interface{}, req interface{}) *MockClient_CreateBatch_Call {
	return &MockClient_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, req)}
}

func (_c *MockClient_CreateBatch_Call) Run(run func(ctx context.Context, req anthropic.BatchRequest)) *MockClient_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(anthropic.BatchRequest))
	})
	return _c
}

func (_c *MockClient_CreateBatch_Call) Return(_a0 *anthropic.BatchResponse, _a1 error) *MockClient_CreateBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreateBatch_Call) RunAndReturn(run func(context.Context, anthropic.BatchRequest) (*anthropic.BatchResponse, error)) *MockClient_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMessage provides a mock function with given fields: ctx, req
func (_m *MockClient) CreateMessage(ctx context.Context, req anthropic.MessageRequest) (*anthropic.MessageResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 *anthropic.MessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, anthropic.MessageRequest) (*anthropic.MessageResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, anthropic.MessageRequest) *anthropic.MessageResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*anthropic.MessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, anthropic.MessageRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MockClient_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - req anthropic.MessageRequest
func (_e *MockClient_Expecter) CreateMessage(ctx interface{}, req interface{}) *MockClient_CreateMessage_Call {
	return &MockClient_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, req)}
}

func (_c *MockClient_CreateMessage_Call) Run(run func(ctx context.Context, req anthropic.MessageRequest)) *MockClient_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(anthropic.MessageRequest))
	})
	return _c
}

func (_c *MockClient_CreateMessage_Call) Return(_a0 *anthropic.MessageResponse, _a1 error) *MockClient_CreateMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreateMessage_Call) RunAndReturn(run func(context.Context, anthropic.MessageRequest) (*anthropic.MessageResponse, error)) *MockClient_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatch provides a mock function with given fields: ctx, batchID
func (_m *MockClient) GetBatch(ctx context.Context, batchID string) (*anthropic.BatchResponse, error) {
	ret := _m.Called(ctx, batchID)

	if len(ret) == 0 {
		panic("no return value specified for GetBatch")
	}

	var r0 *anthropic.BatchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*anthropic.BatchResponse, error)); ok {
		return rf(ctx, batchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *anthropic.BatchResponse); ok {
		r0 = rf(ctx, batchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*anthropic.BatchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, batchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatch'
type MockClient_GetBatch_Call struct {
	*mock.Call
}

// GetBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - batchID string
func (_e *MockClient_Expecter) GetBatch(ctx interface{}, batchID interface{}) *MockClient_GetBatch_Call {
	return &MockClient_GetBatch_Call{Call: _e.mock.On("GetBatch", ctx, batchID)}
}

func (_c *MockClient_GetBatch_Call) Run(run func(ctx context.Context, batchID string)) *MockClient_GetBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetBatch_Call) Return(_a0 *anthropic.BatchResponse, _a1 error) *MockClient_GetBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetBatch_Call) RunAndReturn(run func(context.Context, string) (*anthropic.BatchResponse, error)) *MockClient_GetBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatchResults provides a mock function with given fields: ctx, batchID
func (_m *MockClient) GetBatchResults(ctx context.Context, batchID string) (anthropic.BatchResultIterator, error) {
	ret := _m.Called(ctx, batchID)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchResults")
	}

	var r0 anthropic.BatchResultIterator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (anthropic.BatchResultIterator, error)); ok {
		return rf(ctx, batchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) anthropic.BatchResultIterator); ok {
		r0 = rf(ctx, batchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(anthropic.BatchResultIterator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, batchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetBatchResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchResults'
type MockClient_GetBatchResults_Call struct {
	*mock.Call
}

// GetBatchResults is a helper method to define mock.On call
//   - ctx context.Context
//   - batchID string
func (_e *MockClient_Expecter) GetBatchResults(ctx interface{}, batchID interface{}) *MockClient_GetBatchResults_Call {
	return &MockClient_GetBatchResults_Call{Call: _e.mock.On("GetBatchResults", ctx, batchID)}
}

func (_c *MockClient_GetBatchResults_Call) Run(run func(ctx context.Context, batchID string)) *MockClient_GetBatchResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetBatchResults_Call) Return(_a0 anthropic.BatchResultIterator, _a1 error) *MockClient_GetBatchResults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetBatchResults_Call) RunAndReturn(run func(context.Context, string) (anthropic.BatchResultIterator, error)) *MockClient_GetBatchResults_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
