// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	jina "github.com/sells-group/research-cli/pkg/jina"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: ctx, targetURL
func (_m *MockClient) Read(ctx context.Context, targetURL string) (*jina.ReadResponse, error) {
	ret := _m.Called(ctx, targetURL)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *jina.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*jina.ReadResponse, error)); ok {
		return rf(ctx, targetURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *jina.ReadResponse); ok {
		r0 = rf(ctx, targetURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jina.ReadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, targetURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockClient_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - targetURL string
func (_e *MockClient_Expecter) Read(ctx interface{}, targetURL interface{}) *MockClient_Read_Call {
	return &MockClient_Read_Call{Call: _e.mock.On("Read", ctx, targetURL)}
}

func (_c *MockClient_Read_Call) Run(run func(ctx context.Context, targetURL string)) *MockClient_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Read_Call) Return(_a0 *jina.ReadResponse, _a1 error) *MockClient_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Read_Call) RunAndReturn(run func(context.Context, string) (*jina.ReadResponse, error)) *MockClient_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query, opts
func (_m *MockClient) Search(ctx context.Context, query string, opts ...jina.SearchOption) (*jina.SearchResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *jina.SearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...jina.SearchOption) (*jina.SearchResponse, error)); ok {
		return rf(ctx, query, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...jina.SearchOption) *jina.SearchResponse); ok {
		r0 = rf(ctx, query, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jina.SearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...jina.SearchOption) error); ok {
		r1 = rf(ctx, query, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - opts ...jina.SearchOption
func (_e *MockClient_Expecter) Search(ctx interface{}, query interface{}, opts ...interface{}) *MockClient_Search_Call {
	return &MockClient_Search_Call{Call: _e.mock.On("Search",
		append([]interface{}{ctx, query}, opts...)...)}
}

func (_c *MockClient_Search_Call) Run(run func(ctx context.Context, query string, opts ...jina.SearchOption)) *MockClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]jina.SearchOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(jina.SearchOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_Search_Call) Return(_a0 *jina.SearchResponse, _a1 error) *MockClient_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Search_Call) RunAndReturn(run func(context.Context, string, ...jina.SearchOption) (*jina.SearchResponse, error)) *MockClient_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
