// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	jina "github.com/sells-group/research-cli/pkg/jina"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: ctx, targetURL
func (_m *MockClient) Read(ctx context.Context, targetURL string) (*jina.ReadResponse, error) {
	ret := _m.Called(ctx, targetURL)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *jina.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*jina.ReadResponse, error)); ok {
		return rf(ctx, targetURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *jina.ReadResponse); ok {
		r0 = rf(ctx, targetURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jina.ReadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, targetURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockClient_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - targetURL string
func (_e *MockClient_Expecter) Read(ctx interface{}, targetURL interface{}) *MockClient_Read_Call {
	return &MockClient_Read_Call{Call: _e.mock.On("Read", ctx, targetURL)}
}

func (_c *MockClient_Read_Call) Run(run func(ctx context.Context, targetURL string)) *MockClient_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Read_Call) Return(_a0 *jina.ReadResponse, _a1 error) *MockClient_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Read_Call) RunAndReturn(run func(context.Context, string) (*jina.ReadResponse, error)) *MockClient_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
